name: 'Set up the project environment'

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: '3.13'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction --no-root
