name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup project environment
      uses: ./.github/actions/project-setup

    - name: Run tests
      run: |
        poetry run pytest -v

    - name: Run linting with flake8
      run: |
        poetry run flake8 relays.py test_relays.py

    - name: Test main module execution
      run: |
        poetry run python relays.py
