name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup project environment
      uses: ./.github/actions/project-setup

    - name: Run tests
      run: |
        python -m pytest -v

    - name: Test main module execution
      run: |
        python relays.py
